### ISSUE TITLE
How nested can you make behaviours (and actions, considerations etc while we're at it)

### ISSUE THREAD

**Issue by Franz-Inc** [JarkkoPar/Utility_AI_GDExtension#15]
Some additional useful information would be how nested you can make nodes - you mentioned at one point that you can have only 1 layer of Group Nodes (Behaviour, Action or whatever), but can you layer Action Nodes? What if I want to make a behaviour that is 3 nodes deep (Group Behaviour, Behaviour, Sub-behaviour)? The example I am thinking of is related to your Cover example: An AI would have a Behaviour group of Combat State, then Behaviour of In-Cover, and Sub-Behaviour of Leaving Cover, Shooting, Reloaded blah blah....
Right now I'm just doing many Behaviours without the subgrouping, but I'm curious on your thoughts.

Cheers

**Comment by Franz-Inc** [comment]
I thought of another usecase, but for actions:

ActionPickNewPosition
ActionGroupMove = Action BreakCover + ActionMoveToDesiredPosition


Of course I could do this as:
ActionPickNewPosition
Action BreakCover 
ActionMoveToDesiredPosition

But I see an organizational value in grouping the latter two as they will almost always go hand-in-hand (when ever the AI moves, the assumption is that they need to break cover to do so)

**Comment by JarkkoPar** [comment]
You can nest the ActionGroups, SensorGroups and ConsiderationGroups as much as you want and need. Currently only the BehaviourGroup and Behaviour has the nesting limitation. 

My thinking was that the BehaviourGroups are used to activate/deactive or add/remove groups of behaviours. However, thanks to your and @madeleineostoja suggestions to add more signals to the nodes, it makes a lot of sense to support deeper nesting for the Behaviours as well. This would allow hierarchical behaviours, where the agent would try and find the best scoring behaviour within the tree and then emit the signals for the tree somewhat similarly to how the State Tree works.  

I'll look in to adding this as well for the next release or the one after that.

**Comment by Franz-Inc** [comment]
Hi JarrkoPar,

I'm not sure, but I may have run into a bug around this nesting of ConsideationGroups.

See the nested Considerations:
![image](https://github.com/JarkkoPar/Utility_AI_GDExtension/assets/140611427/8628acf7-c806-4373-b6d0-c285eb4168d7)

AmIHealthy is linked to a health sensor, basically giving back %health.
![image](https://github.com/JarkkoPar/Utility_AI_GDExtension/assets/140611427/f6a7e8f1-dcc0-40b8-9f75-a0689f84fe72)
While testing, as you can see, its designed to score a value of 1 if he's near 100% health. However, despite the enemy actually having 100% health, the Score is listed as 0.
I then duplicated the exact node AmIHealthy? (same sensor, same graph etc) and put it in the first Coniseration Group (see AmIHealthy?2)

![image](https://github.com/JarkkoPar/Utility_AI_GDExtension/assets/140611427/33c1a146-c7f9-4387-9e57-07e9686b7741)

And this one gets the correct score of 1.

Perhaps the nested groups in groups don't work as intended? Or did I misunderstand something here?
Thanks!

**Comment by JarkkoPar** [comment]
I did a test scene and nested 10 consideration groups and considerations, and pointed them to a sensor. All of them seemed to work just fine. I looked through the code as well and couldn't find what could cause this issue. 
Is the MyPowerLevel group active?

**Comment by JarkkoPar** [comment]
I could not replicate this issue and I cannot find an error in the code, so I close this issue for now. Please do ping me if you need more support with this @Franz-Inc .
