### ISSUE TITLE
Godot 3 Support

### ISSUE THREAD

**Issue by smks** [JarkkoPar/Utility_AI_GDExtension#3]
Hello! If I wanted to leverage this through Godot 3.X, what are my options?

**Comment by JarkkoPar** [comment]
Hi! I think GDNative would be an option, though I haven't used it myself so I cannot estimate how much work that would be. Here's a link to the GDExample tutorial in the 3.5 docs: https://docs.godotengine.org/en/3.5/tutorials/scripting/gdnative/gdnative_cpp_example.html

It seems that at least the way the nodes and their methods are registered is different.
