### ISSUE TITLE
signal connect disconnect error when queue node in a certain order

### ISSUE THREAD

**Issue by engimaxp** [JarkkoPar/Utility_AI_GDExtension#4]
it may not be a problem, there is a work around now
if you put area2d under the ai node ,when the node is queued free ,godot first queue free the area2d node ,then the utilityai node
the utilityai node deconstruct method will try to disconnect area2d signals and fail
to fix this ,try put the area2d node above the utilityai node, then it will work smoothly

![2023-11-29_19-21](https://github.com/JarkkoPar/Utility_AI_GDExtension/assets/11832788/0f0f1f08-eb53-4b0b-a5a8-f9ad5720f8d0)
![2023-11-29_19-22](https://github.com/JarkkoPar/Utility_AI_GDExtension/assets/11832788/6f5c35b6-58b4-409a-a3f1-a0337d50291d)
![2023-11-29_19-20](https://github.com/JarkkoPar/Utility_AI_GDExtension/assets/11832788/589989d6-1081-47f6-af25-dc7cef618e62)

great work bro

**Comment by engimaxp** [comment]
reproduced in 4.1.3stable

**Comment by JarkkoPar** [comment]
Thank you for reporting this! I've made a fix and at least in my initial tests it seems to be working correctly. I had the same issue with the Visibility sensors as well, so the impact was greater than just the Area2DSearchSpace.
