### ISSUE TITLE
Export Web/Mobile Support

### ISSUE THREAD

**Issue by mlflabs** [JarkkoPar/Utility_AI_GDExtension#6]
Hello, thanks for a great extensions

One question: does it support web/wasm export?

Mike

**Comment by JarkkoPar** [comment]
Hi Mike, 

Sorry for the delayed response. Just now this extension doesn't support web/wasm. This is only because I do not yet know how that works with GDExtension. I'll check out how that works and if I get it working I'll include the support for the 1.5 or 1.6 release.

**Comment by JarkkoPar** [comment]
Hi Mike,

I got it working. Attached you can find the extension wasm-files you can use for testing. Please do report if you find any issues.

[utility_ai_wasm_test.zip](https://github.com/JarkkoPar/Utility_AI_GDExtension/files/13813445/utility_ai_wasm_test.zip)
