### ISSUE TITLE
Add macOS distributions

### ISSUE THREAD

**Issue by madeleineostoja** [JarkkoPar/Utility_AI_GDExtension#7]
The GDExtension doesn't currently ship binaries that support mac (intel or arm64), would it be possible to add them?

**Comment by JarkkoPar** [comment]
I managed to set up cross compiling for macos, but as I don't have a Mac, I cannot test the resulting binaries. 

I've attached the binaries to this message, could you please test if they work? You just need to download the zip, extract it somewhere and then copy the contained utility_ai folder to the addons folder in your Godot project.
 
[utility_ai_macos_test.zip](https://github.com/JarkkoPar/Utility_AI_GDExtension/files/13812454/utility_ai_macos_test.zip)

**Comment by madeleineostoja** [comment]
Haven't dug too deep yet but seems to work well in Godot 4.2!

Only thing to note is that unless it's code signed (needs apple dev license) users will get an "unidentified developer" warning and need to manually allow it to be run in systems settings (one time operation).

**Comment by JarkkoPar** [comment]
Good that it is working! I'm including this unsigned version in 1.5 as an experimental feature until a signed build can be provided.
