### ISSUE TITLE
There is error when run Tutorial 3

### ISSUE THREAD

**Issue by hantaogo** [JarkkoPar/Utility_AI_GDExtension#8]

**Comment by hantaogo** [comment]
UtiltyAINQSSearchSpaces.execute_query(time_budget_usec: int)

The first parameter in Tutorial 3 was not passed, resulting in the inability to run. What is the purpose of this parameter, and what value should be passed?

**Comment by JarkkoPar** [comment]
Thanks for reporting this! It is the time budget for the query in microseconds, i.e. for how long the query is allowed to run. 

If you just want to run the query and see the results, set a value like 4000 and it should have updated the results of the query after the method call. If you set a small value, like 10 for instance, you may need to call the method several times to get the results updated (depends on the search space size and your hardware).
